### ISSUE TITLE
New Token Request - CANTOBONK

### ISSUE THREAD

**Issue by Cantobonkdev** [forteswap/forte-token-registry#4]
Hi there, Colin Pratt asked me to leave these details here:

{
        "name": "CANTOBONK",
        "address": "0x38D11B40D2173009aDB245b869e90525950aE345",
        "symbol": "CBONK",
        "decimals": 9,
        "chainId": 7700,
        "logoURI": "ipfs://QmRX9dYrNkGv9379n4ksma3AM8w14f8ofe25yvqF8Th8dX/1.png"
      }

**Comment by 0xfoobar** [comment]
Great, added!
